// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AgentConfigStatus {
    "platform": string;
    "configured": boolean;
    "matchesCurrentPort": boolean;
    "needsUpdate": boolean;
    "currentBaseUrl": string;
    "targetBaseUrl": string;
    "configPath": string;
    "authPath"?: string;
    "hasState": boolean;
    "lastError"?: string;

    /** Creates a new AgentConfigStatus instance. */
    constructor($$source: Partial<AgentConfigStatus> = {}) {
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("configured" in $$source)) {
            this["configured"] = false;
        }
        if (!("matchesCurrentPort" in $$source)) {
            this["matchesCurrentPort"] = false;
        }
        if (!("needsUpdate" in $$source)) {
            this["needsUpdate"] = false;
        }
        if (!("currentBaseUrl" in $$source)) {
            this["currentBaseUrl"] = "";
        }
        if (!("targetBaseUrl" in $$source)) {
            this["targetBaseUrl"] = "";
        }
        if (!("configPath" in $$source)) {
            this["configPath"] = "";
        }
        if (!("hasState" in $$source)) {
            this["hasState"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentConfigStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentConfigStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentConfigStatus($$parsedSource as Partial<AgentConfigStatus>);
    }
}
